### ISSUE TITLE
Did you ever get this to work?

### ISSUE THREAD

**Issue by k0bura** [MichaelHorsch/ImageResizer.Sitecore.Plugin#1]
I'm trying to get ImageResizer working in Sitecore XP 8.0

**Comment by MichaelHorsch** [comment]
Sorry Jeff,
I haven't looked in a while.  But for others, there was a bug for 8.0 that I've repaired in the master.  I've also added a note that you must supply your own sitecore dll to build.  That said, I recommend you import this code directly into your project.
